### ISSUE TITLE
Error compiling 

### ISSUE THREAD

**Issue by mcorr023** [PlatformLab/HomaModule#19]
I'm trying to compile using AlmaLinux 8.7, but I get this error . Please help.
![IMG-20230131-WA0000](https://user-images.githubusercontent.com/77362051/217119421-3c1f0cdf-f5ed-44cb-a807-afd149932731.jpg)

**Comment by johnousterhout** [comment]
I'm not familiar with AlmaLinux 8.7; how does this relate to the official
Linux Git repo? It appears that the gro.h header file is missing in your
Linux or has moved.

**Comment by mcorr023** [comment]
Hello, it seemed that AlmaLinux 8.7 had an outdated version of Linux, so I was able to compile it using a more updated environment. 
I am a student learning about transport protocols and would like to ask you for detailed instructions on how to implement and test Homa. I am currently struggling to find more descriptive documentation for beginners like myself. 
Thank you so much in advance. @johnousterhout

**Comment by johnousterhout** [comment]
I have updated the README.md file for Homa to include the latest info on
installing/configuring Homa. I also added some "getting started" info on
benchmarking Homa. I suggest that you take the following steps:

* Get Homa installed and configured on your local cluster using
cloudlab/config and cloudlab/install; you may need to modify these scripts,
depending on your local cluster configuration (e.g. the scripts currently
expect nodes to have names "node0, node1, etc.".

* Try using cp_node standalone as described in README.md to measure basic
unloaded latency and throughput

* Try to run the cp_vs_tcp benchmark to run an entire cluster under load.

-John-

**Comment by johnousterhout** [comment]
I'm going to close this issue for now, but feel free to reopen it (or start a new one) if you have questions or problems.

-John-
