### ISSUE TITLE
cp_node should not pre-compute a pseudo-random pattern for the client requests

### ISSUE THREAD

**Issue by pedrogzz18** [PlatformLab/HomaModule#37]
We shouldn't be pre-computing the information about the client requests (servers, lengths of the requests and intervals of time between requests) in the client constructor inside the cp_node.cc file. 

Instead, we could compute these details on-the-fly inside the sender methods for both homa_client and tcp_client using the random generators, as this will not represent a significant impact on the performance of the tests and it will make Homa's benchmark more realistic.

**Comment by johnousterhout** [comment]
Can this issue be closed, given the PR from last month?
