### ISSUE TITLE
Dist.h exposes too many internal details and lacks unit tests.

### ISSUE THREAD

**Issue by alexisbarraza3293** [PlatformLab/HomaModule#38]
The contents of dist.h/dist.cc should be encapsulated into a class and conformed to standard C++ randomization and organize the interface to hide implementation details from the user. The files also need a unit test to ensure all the functions operate as intended.

**Comment by johnousterhout** [comment]
Does the pull request from last month deal with all these issues (i.e. can this issue be closed?)?

**Comment by alexisbarraza3293** [comment]
Yes, I will close the issue
