### ISSUE TITLE
Wireshark dissector

### ISSUE THREAD

**Issue by pmo73** [PlatformLab/HomaModule#41]
Hi, we have implemented a first version of a Wireshark dissector as a plugin which attaches to the IP protocol on the same protocol type as in the kernel module. The dissector then displays in the GUI the recognized header fields and the rest as payload. We would like to provide the first version of the dissector that can be used with the homa kernel module. The question would be, should it come via a pull request into the kernel module or as a separate repository next to the existing repos?

**Comment by johnousterhout** [comment]
This sounds great! I think it would make sense to include it as part of the
kernel module so that it's immediately available to everyone using Homa.
Feel free to submit a pull request; perhaps put this in a subdirectory of
the top-level directory?

-John-

**Comment by pmo73** [comment]
Thanks you for your fast reply. I will open a pull request and add the dissector inside a subdirectory of the top-level directory.

**Comment by pmo73** [comment]
I just created a pull request with the dissector
