### ISSUE TITLE
cp_basic with "large messages" show very odd behavior

### ISSUE THREAD

**Issue by joft-mle** [PlatformLab/HomaModule#45]
Hi Team HOMA, hi John,

Preamble: _This is most likely, I think, not an issue with the HomaModule, but more like a user/knowledge issue. So if I should move the following to a different communication channel, I'm happy to do so. Please advice._

We are currently getting started with the HOMA protocol and the HomaModule in particular. As a first major step we would like to get the HomaModule and the associated `cp_*` test scripts running on our very small in-house 10GBit/s "cluster", nothing remotely fancy. For starters we took `cp_basic`, just 2 nodes and are looking for a successful run-through. This is where we run into the issue that the sub-tests/experiments with "large messages" (500kB, e.g. "homa_1msg_tput") are more or less obviously not producing any siginficant load on the network interfaces.

We commented out other experiments in `cp_basic` and just left e.g. "homa_1msg_tput" uncommented to look at just that. Then the stdout/stderr of `cp_basic` is:

```
$ ./HomaModule-a/util/cp_basic -v -n 2 -s 10
cperf starting at 2023-09-08 12:50:51.943014
Options: --alt_slowdown: False, --client_max: 200, --client_ports: 9, --clients: [0, 1], --cperf_log: cperf.log, --dctcp: False, --debug: False, --delete_rtts: False, --gbps: 0.0, --ipv6: , --log_dir: logs/20230908125051, --mtu: 0, --no_homa_prio: False, --no_rtt_files: True, --nodes: [0, 1], --num_nodes: 2, --plot_only: False, --port_receivers: 1, --port_threads: 3, --protocol: homa, --seconds: 10, --server_ports: 6, --servers: [0, 1], --skip: None, --tcp_client_ports: 9, --tcp_port_receivers: 1, --tcp_port_threads: 1, --tcp_server_ports: 16, --unsched: 0, --unsched_boost: 0, --verbose: True, --workload:
Homa configuration:
  dead_buffs_limit     5000
  dynamic_windows      0
  grant_fifo_fraction  50
  gro_policy           82
  link_mbps            10000
  max_dead_buffs       3245
  max_grantable_rpcs   0
  max_gro_skbs         20
  max_gso_size         10000
  max_nic_queue_ns     2000
  max_incoming         0
  max_overcommit       8
  max_rpcs_per_peer    1
  num_priorities       8
  pacer_fifo_fraction  50
  poll_usecs           50
  reap_limit           10
  resend_interval      10
  resend_ticks         15
  throttle_min_bytes   1000
  timeout_resends      5
  unsched_bytes        10000
Starting homa servers on nodes range(1, 2)
Starting cp_node on node1
Command for node1: server --ports 6 --port-threads 3 --protocol homa
Starting cp_node on node0
Starting homa_1msg_tput experiment with clients range(0, 1)
Command for node0: client --ports 1 --port-receivers 0 --server-ports 1 --workload 500000 --servers 0,1 --gbps 0.000 --client-max 1 --protocol homa --id 0
Recording initial metrics
Command for node1: log Starting homa_1msg_tput experiment
Command for node0: log Starting homa_1msg_tput experiment
Command for node1: log Ending homa_1msg_tput experiment
Command for node0: log Ending homa_1msg_tput experiment
Retrieving data for homa_1msg_tput experiment
Recording final metrics from nodes [0, 1]
Command for node0: stop senders
Command for node0: stop clients
Traceback (most recent call last):
  File "$PATHTO/HomaModule-a/util/cp_basic", line 166, in <module>
    set_sysctl_parameter("net.ipv4.tcp_congestion_control", congestion,
                                                            ^^^^^^^^^^
NameError: name 'congestion' is not defined
```

Of course the evaluation `cp_basic` is doing at the end is failing, since we commented any experiment other than "homa_1msg_tput" (especially the TCP tests).

We then took the `cp_node server` and `cp_node client` command lines shown by `cp_basic` for the experiment "homa_1msg_tput" and executed them on our node0 and node1 respectively (while `homa_prio` is still running from the `cp_basic` invocation). The results/stdout are:

node0:
```
$ pgrep -a homa_prio
1897 bin/homa_prio --interval 500 --unsched 0 --unsched-boost 0
$ cp_node client --ports 1 --port-receivers 0 --server-ports 1 --workload 500000 --servers 0,1 --gbps 0.000 --client-max 1 --protocol homa --id 0
1694170446.906141958 Average message length 500.0 KB, rate 0.00 K/sec, expected BW 0.0 Gbps
1694170447.906504259 Outstanding client RPCs: 1
1694170448.906655629 Clients: 0.00 Kops/sec, 0.00 Gbps out, 0.00 Gbps in, RTT (us) P50 0.00 P99 0.00 P99.9 0.00, avg. req. length -nan bytes
1694170448.906677672 Outstanding client RPCs: 1
1694170449.906809664 Clients: 0.00 Kops/sec, 0.00 Gbps out, 0.00 Gbps in, RTT (us) P50 0.00 P99 0.00 P99.9 0.00, avg. req. length -nan bytes
1694170449.906828062 Outstanding client RPCs: 1
1694170450.906963385 Clients: 0.00 Kops/sec, 0.00 Gbps out, 0.00 Gbps in, RTT (us) P50 0.00 P99 0.00 P99.9 0.00, avg. req. length -nan bytes
1694170450.906981678 Outstanding client RPCs: 1
1694170451.907138367 Clients: 0.00 Kops/sec, 0.00 Gbps out, 0.00 Gbps in, RTT (us) P50 0.00 P99 0.00 P99.9 0.00, avg. req. length -nan bytes
1694170451.907156330 Outstanding client RPCs: 1
^C
```

node1:
```
$ pgrep -a homa_prio
1792 bin/homa_prio --interval 500 --unsched 0 --unsched-boost 0
$ cp_node server --ports 6 --port-threads 3 --protocol homa
1694170435.679299266 Successfully bound to Homa port 4000
1694170435.679520677 Successfully bound to Homa port 4001
1694170435.679893405 Successfully bound to Homa port 4002
1694170435.680120748 Successfully bound to Homa port 4003
1694170435.680386196 Successfully bound to Homa port 4004
1694170435.680606426 Successfully bound to Homa port 4005
```

So, on node1, the server is not reporting anything to stdout/stderr. And on node0 the client is reporting suspicious numbers of "0.00 Gbps".

Looking at the traffic between node0 and node1 via "port mirroring" in our switch, we see that the client is sending out a bunch of DATA packets, which seem to look OK. It stops when the number of exactly 17040 bytes is reached. Apparently the client is using 17040 bytes for the number of "unscheduled packets", right? Then, the client/node0 is sending out a RESEND packet shortly after the last DATA packet, which makes sense, since node0 is expecting a response. Then the server/node1 is replying with a BUSY packet - apparently rejecting the RESEND request. And that is what is then happening over and over again, in a rather slow ping-pong back and forth.

However, the server is somehow reacting to the client's DATA packets by sending one CUTOFFS packet. Repeating the test, the CUTOFFS packet sometimes appears right after the client sent its last DATA packet (reaching 17040 bytes of payload), and sometimes the CUTOFFS packet can be seen in middle of the client's DATA packet burst. The Wireshark screenshot below shows the former case.

* node0: 192.168.250.1
* node1: 192.168.250.2

![homa_1msg_tput](https://github.com/PlatformLab/HomaModule/assets/56249772/d955b7e8-6482-4ee9-846c-145efd1cd7bf)

In further tests, it turned out that using any `--workload` larger than 17040, even 17040, seems to produces that same behavior.

We are working with Ubuntu 18.04 w/ custom Linux 6.1.38 (GCC 7.5.0) and Debian 12 w/ shipped Linux 6.1.38 (GCC 12.2.0). Both show the same result. We also experimented with switching on/off TSO, GSO and GRO - in various combinations, but did not detect any difference. The 2 nodes in question do have old Intel X520-2 10G NIC each - nothing fancy. The nodes are interconnected using an Arista 10G switch. And we used the current `main` branch (74f29a5817fb).

What is especially puzzling to me is, that the client seems to use 17040 bytes as the "unscheduled bytes", where at the same time the `sysctl` setting is left at default (10000 bytes).

I think, we are missing some crucial point?

**Comment by breakertt** [comment]
Please check `NIC support for TSO` section in README and PR #26 maybe useful for you.

**Comment by johnousterhout** [comment]
It appears to me that node1 isn't sending grants back to node0, so no bytes are transmitted after the initial unscheduled packets. Can you gather a bit more information for me? This will take advantage of Homa's internal timetracing mechanism, which provides debugging information at a very detailed level.
* Run a simplified experiment: on node1, run "cp_node server"; on nod0, run "cp_node client --workload 500000". For this experiment you don't need to run homa_prio.
* While the experiment is running, on node0 invoke "sudo sysctl .net.homa.sync_freeze=1". This will cause the client to "freeze" its timetrace, and it will also notify the server to freeze its timetrace, so we'll have a record from both machines covering exactly the same time interval.
* You can now stop the experiment; on node0, invoke "ttprint.py > client.tt" (ttprint.py is in the util directory); on node1, invoke "ttprint.py > server.tt". These commands will extract the timetraces from the kernels. Then send me both of the .tt files; with that information I should be able to figure out what is going wrong. You might also be interested in looking at the files yourself; they provide a nanosecond-scale trace of all the major activities inside the Homa transport.

-John-

P.S. BTW, the CUTOFFS packets are harmless and unrelated to the problem. Servers send these to clients occasionally, based on their current workloads, to tell the clients what priorities to use for unscheduled packets.

**Comment by joft-mle** [comment]
Hi @johnousterhout ,

thank you very much for your message. I'm sorry for my rather late reply here. Unfortunately my week has been packed with (un)related things, including a downtime of our small "cluster".

Find attached two sets of "timetraces" - resulting from the experiment you've described above. Triggered by @breakertt 's comment I've done the same experiment twice:

1. The first one with _TSO enabled_ (and GRO/GSO both enabled) and
  a. [client-tsoOn.tt](https://github.com/PlatformLab/HomaModule/files/12619788/client-tsoOn.txt)
  b. [server-tsoOn.tt](https://github.com/PlatformLab/HomaModule/files/12619790/server-tsoOn.txt)
2. the second one with _TSO disabled_ (and GRO/GSO both enabled).
  a. [client-tsoOff.tt](https://github.com/PlatformLab/HomaModule/files/12619792/client-tsoOff.txt)
  b. [server-tsoOff.tt](https://github.com/PlatformLab/HomaModule/files/12619793/server-tsoOff.txt)

_Note that I renamed the file extension to `.txt` for GitHub to be happy ..._

To me the "timetraces" kind of reflect what I've seen in Wireshark:

1. The client is starting to send those magic (to me at least; why not unsched_bytes = 10000?) 17040 bytes of payload without having an explicit "grant". The server seems to recognize them. So there seems to be no packet loss.
4. Then, I guess, I see some kind of "active waiting" for a GRANT on the client side in the hope to send more,
5. followed by an "endless loop" of RESEND + BUSY after a timeout of 15ms - lasting until I've frozen the trace.

In case of TSO disabled, the "waiting" part seems to be shorter in terms of number of loops. On the server side I currently don't see that much of a difference between TSO disabled and enabled. The chronological order of events and their distance seems to also reflect what's visible from Wireshark.

Other than that, to my untrained eye, nothing does stand out yet regarding the issue.

The experiments have been run on Debian 12 w/ shipped Linux 6.1.38 (GCC 12.2.0) and those old Intel X520-2 10G NICs.

**Comment by johnousterhout** [comment]
I think I have found the problem: Homa's "max_incoming" parameter is at the default value of 0, which prevents any grants from being issued. Try issuing the following command on each of your nodes and see if the test now finishes.
```
sudo sysctl .net.homa.max_incoming=500000
```
The default of 0 is a misfeature on Homa's side; I have changed it to something more reasonable.  However, it also appears that you're not configuring Homa, which is likely to cause sub-par performance. There is a Python script `cloudlab/bin/config` that I run on each node to install and configure Homa on the CloudLab testbed where I work. I'd suggest that you also run this script; it will probably error out because it can't identify your cluster type (in the config_homa method). You'll probably need to modify the config script a bit to match your environment.

Finally the 17040 vs. 10000 bytes of unscheduled data is because unsched_bytes is a minimum: Homa will round this up to the next full outgoing packet, which is 17040 in your experiment.

Let me know if things work with this change?

-John-

**Comment by joft-mle** [comment]
Hi @johnousterhout ,

thank you very much for your reply. I can report that after setting `net.homa.max_incoming`, we seem to be getting somewhere. `cp_basic` does seem to run through successfully now - _with_ obviously actual "data traffic" in each case according to switch port counters. And "sending grant" messages can be seen in timetrace dumps.

Regarding `cloudlab/bin/config`: Yes, I did see that script, but previously came to the (now wrong) conclusion that the `cp_*` experiments should _basically_ work without it, since the built-in `sysctl` defaults somehow looked to me like they might match a 10Gbit/s network. That's where I obviously failed to spot the `max_incoming` setting. We also still have to look at our Arista 7050QX switch and see what settings are possible regarding those mentioned in `cloudlab/bin/config`. Next to Homa and Switch configuration, `cloudlab/bin/config` seems to, as third important thing, enable RPS/RFS on the used interfaces.

Regarding 17040 bytes: Ok, understood. So this most likely depends on how big a GSO "packet" can get, since it cannot be related to the current MTU (1500). I'm sure I'll come across it as I continue to study the code.

So, as the original issue is out of the way, I guess we can close this one here. Thanks again!
