### ISSUE TITLE
How does Homa perform against TCP_NODELAY sockets?

### ISSUE THREAD

**Issue by zz090923610** [PlatformLab/HomaModule#51]
Hi @johnousterhout I just read your ATC 21 Homa paper and found that this is really an interesting project! However I have some questions, the paper says that Homa can outperform TCP by a huge number of times for small payloads. Does the TCP compared there just plain TCP connections? Or the TCP connections configured with TCP_NODELAY option which can reduce the latency a lot? If not the NODELAY sockets, how does Home perform compared against TCP_NODELAY sockets? Thanks!

**Comment by johnousterhout** [comment]
All of the TCP measurements in the ATC 21 Homa paper use TCP_NODELAY.
