### ISSUE TITLE
__attribute__((unused)) for used variables

### ISSUE THREAD

**Issue by amjal** [PlatformLab/HomaModule#57]
__argc__ and __argv__ are used in the test_harness_run function body. The __unused__ attributes [here](https://github.com/PlatformLab/HomaModule/blob/a3fb70e6bd3439e39696b783e3831bbd23787c17/test/kselftest_harness.h#L825) seem to be leftover from previous builds? It's a little confusing to me.

**Comment by johnousterhout** [comment]
Yep, those are stale. I just removed them. Thanks for reporting.
